import type { VercelRequest, VercelResponse } from '@vercel/node';
import crypto from 'crypto';

const CREEM_WEBHOOK_SECRET = process.env.CREEM_WEBHOOK_SECRET || '';

function verifySignature(payload: string, signature: string, secret: string): boolean {
  if (!secret) return true; // Skip verification if no secret configured
  
  const expectedSignature = crypto
    .createHmac('sha256', secret)
    .update(payload)
    .digest('hex');
  
  return crypto.timingSafeEqual(
    Buffer.from(signature),
    Buffer.from(expectedSignature)
  );
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const signature = req.headers['x-creem-signature'] as string;
  const rawBody = JSON.stringify(req.body);

  // Verify webhook signature if secret is configured
  if (CREEM_WEBHOOK_SECRET && !verifySignature(rawBody, signature, CREEM_WEBHOOK_SECRET)) {
    console.error('Invalid webhook signature');
    return res.status(401).json({ error: 'Invalid signature' });
  }

  const event = req.body;

  console.log('Received Creem webhook:', event.type, event);

  try {
    switch (event.type) {
      case 'checkout.completed':
        // Payment successful - license key should be generated by Creem
        // The user will receive the license key via email from Creem
        console.log('Checkout completed:', {
          email: event.data?.customer_email,
          licenseKey: event.data?.license_key,
          productId: event.data?.product_id,
        });
        break;

      case 'license.created':
        // New license created
        console.log('License created:', {
          key: event.data?.key,
          email: event.data?.customer_email,
        });
        break;

      case 'license.activated':
        console.log('License activated:', event.data);
        break;

      case 'license.deactivated':
        console.log('License deactivated:', event.data);
        break;

      case 'subscription.cancelled':
        console.log('Subscription cancelled:', event.data);
        break;

      default:
        console.log('Unhandled event type:', event.type);
    }

    return res.status(200).json({ received: true });
  } catch (error) {
    console.error('Webhook processing error:', error);
    return res.status(500).json({ error: 'Webhook processing failed' });
  }
}

// Disable body parsing to get raw body for signature verification
export const config = {
  api: {
    bodyParser: true, // Vercel handles this differently, keep true
  },
};
