import type { VercelRequest, VercelResponse } from '@vercel/node';
import crypto from 'crypto';

const CREEM_WEBHOOK_SECRET = process.env.CREEM_WEBHOOK_SECRET || '';

function verifySignature(payload: string, signature: string, secret: string): boolean {
  if (!secret) return true; // Skip verification if no secret configured
  
  const expectedSignature = crypto
    .createHmac('sha256', secret)
    .update(payload)
    .digest('hex');
  
  return crypto.timingSafeEqual(
    Buffer.from(signature),
    Buffer.from(expectedSignature)
  );
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const signature = req.headers['creem-signature'] as string || req.headers['x-creem-signature'] as string;
  const rawBody = JSON.stringify(req.body);

  // Verify webhook signature if secret is configured
  if (CREEM_WEBHOOK_SECRET && !verifySignature(rawBody, signature, CREEM_WEBHOOK_SECRET)) {
    console.error('Invalid webhook signature');
    return res.status(401).json({ error: 'Invalid signature' });
  }

  const event = req.body;

  console.log('Received Creem webhook:', event.type, JSON.stringify(event, null, 2));

  try {
    switch (event.type) {
      case 'checkout.completed':
        // Payment successful - license key should be generated by Creem
        // The user will receive the license key via email from Creem
        console.log('Checkout completed:', {
          email: event.data?.customer?.email,
          customerId: event.data?.customer?.id,
          productId: event.data?.product?.id,
          subscriptionId: event.data?.subscription?.id,
        });
        break;

      case 'subscription.active':
        // New subscription created and payment collected
        console.log('Subscription activated:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
          status: event.data?.status,
          currentPeriodEnd: event.data?.current_period_end_date,
        });
        break;

      case 'subscription.paid':
        // Subscription payment successful (includes renewals)
        // Creem automatically extends the license expiration date
        // Our /api/license/verify endpoint will return the updated expires_at
        console.log('Subscription paid (renewal processed):', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
          status: event.data?.status,
          currentPeriodEnd: event.data?.current_period_end_date,
        });
        break;

      case 'subscription.canceled':
        // Subscription was canceled
        console.log('Subscription canceled:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
        });
        break;

      case 'subscription.scheduled_cancel':
        // Subscription will cancel at end of billing period
        console.log('Subscription scheduled for cancellation:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
          cancelAt: event.data?.current_period_end_date,
        });
        break;

      case 'subscription.past_due':
        // Payment failed, subscription is past due
        console.log('Subscription past due:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
        });
        break;

      case 'subscription.expired':
        // Subscription expired without payment
        console.log('Subscription expired:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
        });
        break;

      case 'subscription.trialing':
        // Subscription started trial period
        console.log('Subscription trial started:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
        });
        break;

      case 'subscription.update':
        // Subscription was updated
        console.log('Subscription updated:', {
          subscriptionId: event.data?.id,
          customerId: event.data?.customer?.id,
          status: event.data?.status,
        });
        break;

      case 'refund.created':
        // Refund was issued
        console.log('Refund created:', {
          refundId: event.data?.id,
          amount: event.data?.amount,
        });
        break;

      case 'dispute.created':
        // Customer initiated a dispute
        console.log('Dispute created:', {
          disputeId: event.data?.id,
        });
        break;

      default:
        console.log('Unhandled event type:', event.type);
    }

    return res.status(200).json({ received: true });
  } catch (error) {
    console.error('Webhook processing error:', error);
    return res.status(500).json({ error: 'Webhook processing failed' });
  }
}

// Disable body parsing to get raw body for signature verification
export const config = {
  api: {
    bodyParser: true, // Vercel handles this differently, keep true
  },
};
